### ISSUE TITLE
Split combined borehole 163

### ISSUE THREAD

**Issue by ezwelty** [mjacqu/glenglat#92]
Borehole 163 from odegard1997 is the combination of a 100 m borehole (temperature_uncertainty: 0.05, installed 1994-04-28) and a 52 m borehole (temperature_uncertainty: 0.03, installed 1995-04-02) 5 m apart. These should be split apart. They were drilled (and likely measured) in different years.

**Comment by mjacqu** [comment]
@ezwelty I decided (let me know if you want me to do this differently) to keep them as one borehole (and one profile), but updated the notes with additional uncertainty and the profile.min_date and profile.max_date with possible date range. Otherwise we have two profiles with the same data, which also seem inconsistent?
